Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = "worker02"
  config.vm.network "private_network", ip: "10.0.100.13"

  config.vm.provider :virtualbox do |v|
    v.name = "worker02"
    v.memory = 1024
    v.cpus = 2
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../playbooks/config.yaml"
  end
end
