Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = "controller01"
  config.vm.network "private_network", ip: "10.0.100.11"

  config.vm.provider :virtualbox do |v|
    v.name = "controller01"
    v.memory = 3072
    v.cpus = 2
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../playbooks/controller_config.yaml"
  end

  config.vm.synced_folder "../../kiamol", "/kiamol"
end
