Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "nfs01"
  config.vm.network "private_network", ip: "10.0.100.15"

  config.vm.provider :virtualbox do |v|
    v.name = "nfs01"
    v.memory = 1024
    v.cpus = 2
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../playbooks/nfs_server.yaml"
  end
end
