---

- hosts: all
  become: true
  tasks:
    - name: disable swap
      shell: |
        swapoff -a

    - name: comment swap in /etc/fstab
      replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
        replace: '# \1'

    - name: install packages
      apt:
        name:
          - curl
          - apt-transport-https
          - ca-certificates
          - gnupg
          - lsb-release
        state: present

    - name: add docker gpg key
      shell: >
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
    
    - name: add docker repository
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu focal stable"
        filename: docker.list
        state: present
        update_cache: true

    - name: add kubernetes gpg key
      shell: >
        curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -

    - name: add kubernetes repository
      apt_repository:
        repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main"
        state: present
        update_cache: true

    - name: install docker and kubernetes
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose
          - kubelet=1.22.0-00
          - kubeadm=1.22.0-00
          - kubectl=1.22.0-00

    - name: hold kubernetes' version
      dpkg_selections:
        name: "{{ item }}"
        selection: hold
      with_items:
        - kubelet
        - kubeadm
        - kubectl

    - name: update kernel setting for flannel
      sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: 1
        sysctl_set: yes
        state: present
        reload: yes

    - name: Change cgroup driver
      copy:
        src: ../files/daemon.json
        dest: /etc/docker/daemon.json
        owner: root
        group: root
        mode: '0644'

    - name: Reload systemd config
      systemd:
        daemon_reload: yes

    - name: Restart docker service
      systemd:
        state: restarted
        name: docker

    - name: reboot the machine
      reboot:

    - name: Join k8s cluster
      script: ../join_command.sh
