---

- hosts: all
  become: true
  tasks:
    - name: Install container runtime and k8s tools
      include_tasks: container_runtime_k8s_tools.yaml

    - name: Join k8s cluster
      script: ../join_command.sh
