---

- hosts: all
  become: true
  tasks:
    - name: Install container runtime and k8s tools
      include_tasks: container_runtime_k8s_tools.yaml

    - name: Create NFS mount point
      file:
        path: /var/nfsshare
        state: directory

    - name: Mount NFS share
      mount:
        src: 10.0.100.15:/nfsexport
        path: /var/nfsshare
        opts: defaults
        state: mounted
        fstype: nfs

    - name: kubeadm init
      command: kubeadm init --pod-network-cidr="10.244.0.0/16" --service-cidr="10.96.0.0/12" --apiserver-advertise-address="10.0.100.11"

    - name: Make .kube dir
      file:
        path: /root/.kube
        state: directory

    - name: Copy kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /root/.kube/config
        mode: u+r,g+r
        remote_src: yes

    - name: Install Calico
      command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml 

    - name: Register join token
      command: kubeadm token create --print-join-command
      register: join_command

    - name: Save kubeadm join command
      become: 
      local_action:
        module: copy
        content: "{{ join_command.stdout }}"
        dest: ../join_command.sh

    - name: Install helm
      shell: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Install csi-driver-nfs
      shell: |
        helm repo add csi-driver-nfs https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
        helm install csi-driver-nfs csi-driver-nfs/csi-driver-nfs --namespace kube-system --version v4.9.0
